{
 "title": "Temperature and Humidity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last update",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select time from dht11\r\norder by\r\n  time desc\r\nlimit 1",
     "rawQueryText": "select time from dht11\r\norder by\r\n  time desc\r\nlimit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT temperature FROM DHT11\norder by\n  time desc\nlimit 1",
     "rawQueryText": "SELECT temperature FROM DHT11\norder by\n  time desc\nlimit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT humidity FROM DHT11\norder by\n  time desc\nlimit 1",
     "rawQueryText": "SELECT humidity FROM DHT11\norder by\n  time desc\nlimit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature and Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "queryText": "SELECT time, temperature, humidity from DHT11",
     "rawQueryText": "SELECT time, temperature, humidity from DHT11",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}